apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-docker
  name: load-balancer
spec:
  ports:
  - nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: react-docker
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-docker
  template:
    metadata:
      labels:
        app: react-docker
    spec:
      containers:
      - image: puttehi/react-docker
        name: react-docker
        ports:
        - containerPort: 80
